### ISSUE TITLE
I18N Text Domain Issue

### ISSUE THREAD

**Issue by alexclassroom** [akshuvo/load-more-anything#11]
- This plugin's slug is `ajax-load-more-anything`, but the current Text Domain is `aldtd`. Change the current Text Domain so it is equal to this plugin's slug and modify the text domain in all your source files. This change is **needed**, please refer to [this article](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains).
- **"Requires at least"** (1.0) is below 4.6 so a `load_plugin_textdomain` is **needed**, please refer to [this article](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain).
- Please notice the string Setting with different wrong Text Domain, it also needs to be fixed as `ajax-load-more-anything`.

**Comment by akshuvo** [comment]
@alexclassroom  thanks for your comment. We're working on it.

**Comment by akshuvo** [comment]
the mentioned issues are fixed.
