### ISSUE TITLE
Load More Button

### ISSUE THREAD

**Issue by shobhitsaxena-coderazor** [akshuvo/load-more-anything#3]
I am using your plugin **'Load More Anything'** to add a load more functionality to the website, but after using that if there is nothing to show or only 2-3 data are available to show, it still shows the load more button.

How can I prevent it to show the load more button if data is not available or fewer data to show. Please guide me so that I can use it.

Thanks in advance

**Comment by shobhitsaxena-coderazor** [comment]
Still waiting for your reply.

**Comment by akshuvo** [comment]
Can you show me the setup you did?

**Comment by akshuvo** [comment]
please use the updated version of the plugin.
