### ISSUE TITLE
Cannot translate the "load More" button label

### ISSUE THREAD

**Issue by edgeg2242** [akshuvo/load-more-anything#5]
Tried PHP, tried shortcode, nothing works. Tried to reach you by email, no luck. Any trick to do it via shortcode or php?

**Comment by akshuvo** [comment]
I am working on this issue. I Will let you updates soon.

**Comment by edgeg2242** [comment]
For now a quick fix to insert php or Shortcode will do the trick meanwhile you come up with a new/final version. Which syntax would work for inserting one of these two (php or shortcode)? Thanks for your help. Much appreciated !

**Comment by akshuvo** [comment]
Please update the plugin from WordPress Dashboard to the latest. You can now translate Load More Button Label using Loco Translate Plugin. Check FAQ in the plugin description.

**Comment by edgeg2242** [comment]
Thank you very much for this pro-activity. This said, it is not the plugin itself that I want to translate, it's only the label "Load More".
![image](https://user-images.githubusercontent.com/88452309/128286840-92c1dff8-2f7f-48fa-95cf-3519f90af430.png)

I'm having hard time understanding your FAQ translation description (when you are talking about editing the "template", are you talking about your .po translation file?).
 
Also I already using WPML for my entire site. It is kind of unproductive to install Loco plugin only for two label strings (I use 2/6 of your wrappers). Would it be a problem?

Thank you for taking time with me.

**Comment by akshuvo** [comment]
I also have the option in your WPML where you can add a String and Translate it using WPML.

**Comment by edgeg2242** [comment]
I'm presently using the 2.4.6 version
After scanning your plugin for new strings, here is the total of what I found:
![image](https://user-images.githubusercontent.com/88452309/128375829-80af4084-c1c4-4265-8f5d-ca7c8605457e.png)
![image](https://user-images.githubusercontent.com/88452309/128376083-f6ee7e51-9c3a-4488-bd55-ab1e2f9fe8ea.png)
![image](https://user-images.githubusercontent.com/88452309/128376217-a6a67d48-288b-4686-8397-141bfb9e64b6.png)
![image](https://user-images.githubusercontent.com/88452309/128376300-254e3604-dab8-4c18-92f0-6f015cf55a5b.png)


----------------------------------------------------------


So what are the names (or IDs) of the 6 new "load more" label strings?
![image](https://user-images.githubusercontent.com/88452309/128376858-8b725571-dc41-47ee-8c7f-4b54fb1165aa.png)

**Comment by edgeg2242** [comment]
Any news ?

**Comment by s1awek** [comment]
What I've done is combination of shortcoe and `button_label=`:

```
<?php echo do_shortcode('[ajax_load_more  button_label="' . __('Load more', 'my-domain') . '" transition="masonry" masonry_selector=".c-news" archive="true" post_type="post" scroll="false" posts_per_page="' . BLOG_PER_PAGE . '"]'); ?>
```

Works lika a charm.

**Comment by akshuvo** [comment]
We will update the plugin soon, there you’ll able to translate button label. 

Thanks all for your contributions.

**Comment by akshuvo** [comment]
please use the updated version of the plugin. The issue has been fixed
