### ISSUE TITLE
Need to increase Flex Display wrapper container quantity for free version plugin

### ISSUE THREAD

**Issue by sayantannag** [akshuvo/load-more-anything#6]
Only one Flex Display wrapper container available into free version of plugin, which is not worthy because in today’s date every website built with bootstrap, we need at least three to four Flex Display wrapper in free version to check this plugin usability.

Previously I’ve set one Load More Flex wrapper for one page from backend of Plugin setting area, It’s working fine. But when I put another flex based container into a normal wrapper container from backend it’s not work for the new page then. It’s really a serious issue. In this way it is not worthy for anyone actually.

**Comment by akshuvo** [comment]
please use the updated version of the plugin. The issue has been fixed
